import type { Metadata } from 'next';
import { poppins } from '../../public/fonts/fonts';
import './globals.css';
import Image from 'next/image';
import evolve_icon from '../../public/assets/evolve-dark-2.png';
import { bebas_neue } from '../../public/fonts/fonts';

export const metadata: Metadata = {
	title: 'Evolve',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={poppins.className}>{children}</body>
		</html>
	);
}
